project:
  type: website
  output-dir: docs

website:
  title: "MRNE/ENST 222"
  page-navigation: true
  favicon: "images/favicon/favicon.ico"
  site-url: "https://mrne222-sp26.github.io/website/"
  repo-url: "https://github.com/MRNE222-sp26-activities/"
  sidebar:
    style: "docked"
    search: true
    logo: "images/enst222_hex.png"
    alignment: "left"
    pinned: true
    tools:
      - icon: github
        href: "https://github.com/MRNE222-sp26-activities/"
        text: "GitHub organization"
      - icon: code-square
        href: "https://posit.cloud/spaces/742577/join?access_code=aniqlj6EfZVcx9myIb3blIdMJmYA8bS7KL5i4kq0"
        text: "Posit Cloud"
      
    contents:
      - href: index.qmd
        text: Welcome
      - 01-syllabus.qmd
      - 02-schedule.qmd
      - 03-project.qmd
      - 05-help.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

